spring:
  kafka:
    properties:
      bootstrap.servers: localhost:11091
      security.protocol: SSL
      group.id: spring-sample-consumer
      ssl:
        keystore:
          location: /tmp/kafka.client.keystore.jks # WARN: On a production system, the keystore should be in a safe place!
          password: confluent
        truststore:
          location: /tmp/kafka.client.truststore.jks # WARN: On a production system, the truststore should be in a safe place!
          password: confluent


